image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 3306 # MySQL
  onOpen: ignore
- port: 9009
  onOpen: ignore
- port: 8080
  onOpen: open-preview


# start up tasks
tasks:
  # init: Will be executed one time when creating a workspace, command: will be exected each time you open workspace
  - init: |
      composer update --no-interaction --prefer-dist
      php artisan migrate
      php artisan db:seed
    command: |
      .      php artisan serve
  # - command: gp await-port 8080 && ./vendor/bin/codecept run --coverage
  - command: gp await-port 8080 && gp preview $(gp url 8080)